### PR TITLE
fix search state

### PR DESCRIPTION
**Pull request by juanse1801**
Co-Authored-By: Eduardo Salinas <75259006+eduardo-salinas@users.noreply.github.com>
Co-Authored-By: Juan Condori <78325127+juancdri@users.noreply.github.com>
Co-Authored-By: Mr .reverse <75991527+julianmondaca@users.noreply.github.com>
Co-Authored-By: Manuel Sosa <71500229+manuelnsosa@users.noreply.github.com>
Co-Authored-By: marianavinyolas <49161320+marianavinyolas@users.noreply.github.com>
Co-Authored-By: Tomas Buzzalino <tomibuzzalino@gmail.com>
Co-Authored-By: Emiliano Meneses <65609474+itsnou@users.noreply.github.com>

### CODE REVIEW

**Review by itsnou — APPROVED** [review]

**Comment by tbuzzalino** [comment]
Well done

**Comment by manuelnsosa** [comment]
Aprobado

**Comment by eduardo-salinas** [comment]
ok

**Review by tbuzzalino — APPROVED** [review]

**Review by manuelnsosa — COMMENTED** [review]
Well done

**Review by eduardo-salinas — APPROVED** [review]

**Review by julianmondaca — APPROVED** [review]

**Review by juancdri — APPROVED** [review]

**Review by marianavinyolas — APPROVED** [review]
Solved!!!!!

**Pull request merged**
